<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="base_length" value="0.55" />

  <xacro:property name="base_width" value="0.28" />
  <xacro:property name="base_height" value="0.003" />
  <xacro:property name="base_mass" value="1" />
  <xacro:property name="wheel_radius" value="0.0625" />
  <xacro:property name="wheel_width" value="0.04" />
  <xacro:property name="wheel_pos_x" value="0.0" />
  <xacro:property name="offset_x" value="${base_length/2-0.055}" />
  <xacro:property name="wheel_pos_y" value="${base_width/2+wheel_width/2+0.01}" />

  <xacro:property name="wheel_pos_z" value="${-wheel_radius+0.0005}" />
  <xacro:property name="wheel_mass" value=".1" />
  <xacro:property name="wheel_torque" value="20" />
  <xacro:property name="front_caster_wheel" value="true" />
  <xacro:property name="rear_caster_wheel" value="false" />

  <xacro:property name="laser_pose">
    <!-- zbot lino 1.5 rplidar -->
    <origin xyz="${base_length/2+offset_x-0.085} 0 0.088" rpy="0 0 0"/>
  </xacro:property>

  <xacro:property name="laser_pose_nanoscan3_front">
    <origin xyz="${base_length/2+offset_x-0.06} 0 0.14" rpy="0 0 0"/>
  </xacro:property>

  <xacro:property name="laser_pose_front_inverted">
    <origin xyz="${base_length/2+offset_x} 0 0.088" rpy="3.1415 0 0"/>
  </xacro:property>

  <xacro:property name="depth_sensor_pose">
    <origin xyz="${0.2+offset_x} 0.0 0.045" rpy="0 0 0"/>
  </xacro:property>
</robot>
